# Generated by Django 3.2.7 on 2021-09-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(default=1, upload_to='posts/'),
            preserve_default=False,
        ),
    ]
